Delete answer from dashboard
rage/quizzes pull request #687
Opened 2021-02-03 10:07 UTC by HegePI

2021-02-15 14:00 UTC, nygrenh requested changes

2021-02-26 12:32 UTC, HegePI commented on packages/quizzes-dashboard/components/Answer/index.tsx
> +  $faded: boolean
$ ????

2021-03-01 13:17 UTC, nygrenh requested changes

2021-03-01 13:17 UTC, nygrenh commented on packages/backendv2/src/controllers/dashboard/util.ts
> +  assistant: ["view", "edit", "grade", "delete"],
rename to `delete-answers`

2021-03-01 13:17 UTC, nygrenh commented on packages/backendv2/src/models/quiz_answer.ts
> +          status: "open",
make this locked if new userQuizState.tries >= quiz.tries

2021-03-02 08:21 UTC, nygrenh approved these changes

2021-03-02 08:21 UTC, merged