Multiple choices rework
rage/quizzes pull request #782
Opened 2021-05-11 07:10 UTC by sebazai

Currently Quizzes ver. 0.9.10 only works on Ohjelmointi-21.
Latest version crashes because Ohjelmointi-21 has many quiz items in one quiz.

For Economics MOOC we want to show feedback for each answer option, this is something that we don't want in ohjelmointi-21, even though they have unlimited tries.

Fixes #781 :
- [x] Show quiz title regardless direction (Hopefully fine for Economics, that uses column a lot)
- [x] Shows the correct failure/success message if many quiz items (?)
- [x] Some minor refactoring, which could break things.

To do (Comments please):
- [x] We need some backend to toggle the option "showFeedbackForEachAnswerOption" ?
  - [x] Once we have this, work on the widget to take this into account
- [ ] Test functionality
- [ ] Make sure this works on Economics, Elements and Ohjelmointi-21 (is there any way to do this without publishing version?)

![image](https://user-images.githubusercontent.com/39335537/117772995-76759300-b240-11eb-8043-a52b66ffcfee.png)

2021-05-11 11:42 UTC, sebazai commented
![image](https://user-images.githubusercontent.com/39335537/117809039-535dda00-b266-11eb-9418-5bf4d7f54335.png)

Is this the correct checkbox/boolean to be toggled for a Quiz Item to handle showing feedback for each answer or feedback for quiz item the whole quiz item?

2021-05-12 14:22 UTC, nygrenh commented
```
enum QuizItemFeedbackDisplayPolicy {
  DisplayFeedbackOnQuizItem,
  DisplayFeedbackOnAllOptions,
}
```

2021-05-24 12:45 UTC, nygrenh requested changes

2021-05-24 12:45 UTC, nygrenh commented on packages/backendv2/database/migrations/20210518162600_quiz_display_policy.ts
> +    table.dropColumn("feedback_display_policy")
Also drop enum

2021-05-24 12:45 UTC, nygrenh commented on packages/moocfi-quizzes/src/components/MultipleChoice.tsx
> +  const selectedOption = showFeedbackForEachAnswerOption
misleading name

2021-05-24 12:45 UTC, nygrenh commented on packages/moocfi-quizzes/src/components/MultipleChoice.tsx
> +  const itemAnswersUnlimitedTries = showFeedbackForEachAnswerOption
misleading name

2021-05-24 12:45 UTC, nygrenh commented on packages/moocfi-quizzes/src/components/MultipleChoice.tsx
> +  const correct = showFeedbackForEachAnswerOption
Should this be read from the server response

2021-05-24 12:45 UTC, nygrenh commented on packages/quizzes-dashboard/components/QuizEditForms/QuizItem/MultipleChoiceContent/MultipleChoiceModalContent.tsx
> +        <TextField
Should be `Select`

2021-05-24 14:46 UTC, sebazai commented on packages/backendv2/database/migrations/20210518162600_quiz_display_policy.ts
> +    table.dropColumn("feedback_display_policy")
Should drop.

2021-05-31 12:15 UTC, nygrenh approved these changes

2021-05-31 12:15 UTC, merged